### ISSUE TITLE
Remove unrecoverable errors from the interface

### ISSUE THREAD

**Issue by favonia** [RedPRL/algaett#18]
~~@mmcqd @jonsterling Currently, each top-level module (directories) has its own error type, and that's probably leading to lots of boilerplate with little benefit. Proposals:~~

0. ~~Keep the current principle~~
1. ~~Centralize all errors into one place~~

~~I wonder if there are any other counter proposals, no matter how stupid they might sound?~~

**Comment by TOTBWF** [comment]
For unrecoverable errors, I don't see much of a use for trying to encode these in sum types; it seems the best option is to turn them into some sort of structured error type (error message, error code, etc) and throw upwards.

**Comment by jonsterling** [comment]
I agree with @TOTBWF

**Comment by jonsterling** [comment]
In fact, are there even **any** errors that ought to be "recoverable"? It seems that to really recover from an error one needs the continuation, but that is an effect and not an exception.

**Comment by favonia** [comment]
Closed by #28
