### ISSUE TITLE
The new Refiner does not handle Unfold correctly

### ISSUE THREAD

**Issue by favonia** [RedPRL/algaett#9]
@jonsterling I am still debugging it.

**Comment by favonia** [comment]
@jonsterling I believe the issue is that none of those tactics handled `Unfold`. The original `check` can easily "cheat" with a flag because all the tactics were "centralized". What's missing now is the logic in these lines:

https://github.com/RedPRL/algaett/blob/6877ea3533b283962a3660b4d24668d96481dfe3/src/checker/Elaborator.ml#L183-L186

I am not sure how to address this---certainly we want to keep the current decentralized framework. My intuition is actually to use algebraic effects to "ask for help in unfolding" but that might be overkill :laughing: What should we do? There seem to be too many ways to make it work, and I have not developed the Principle to pick one.

**Comment by favonia** [comment]
> When I rewrote the code, I was careful to include logic that reflects the logic of your original code for handling Unfold.

Only partially, due to the subtlety of pattern matching. The previous line

https://github.com/RedPRL/algaett/blob/6877ea3533b283962a3660b4d24668d96481dfe3/src/checker/Elaborator.ml#L159

which will *not* be triggered if `tp` is `Unfold`. Now, it is

https://github.com/RedPRL/algaett/blob/5685e49608aaf230f5691f3e339cd2bd3acb6ec9/src/elaborator/Elaborator.ml#L88

which would fire no matter what `tp` is (unfolded or not). The minimum example is actually in the README: :laughing: 
```
📌 😄 : 🌌 🆙 2️⃣ 👉 🌌 🆙 1️⃣
📌 _ 👉 🌌 : 😄
```
Or, in a less Immortal :place_of_worship: syntax:
```
def 😄 : univ^2 := univ^1
def _ := univ : 😄
```

**Comment by jonsterling** [comment]
Thanks, this helps! I'll think a bit about the right way to handle this.
